"""account repeat metrics

Revision ID: 417dd0278b7a
Revises: 64eece8ad7bc
Create Date: 2026-06-30 16:04:22.956434
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '417dd0278b7a'
down_revision: str | None = '64eece8ad7bc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'accounts',
        sa.Column('is_repeating', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'accounts',
        sa.Column('repeat_order_count', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column('accounts', sa.Column('last_order_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_accounts_is_repeating'), 'accounts', ['is_repeating'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_is_repeating'), table_name='accounts')
    op.drop_column('accounts', 'last_order_at')
    op.drop_column('accounts', 'repeat_order_count')
    op.drop_column('accounts', 'is_repeating')
    # ### end Alembic commands ###
