"""core entities

Revision ID: 4d8b94a729cb
Revises: 0001_enable_postgis
Create Date: 2026-06-25 23:06:22.874777
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision: str = '4d8b94a729cb'
down_revision: str | None = '0001_enable_postgis'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pack_size', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('manager', 'rep', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_geospatial_table('accounts',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('grocery_store', 'wholesaler', 'restaurant', 'caterer', 'vendor', name='account_category'), nullable=False),
    sa.Column('status', sa.Enum('lead', 'in_discussion', 'sampled', 'trial', 'repeat', 'not_interested', name='account_status'), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_rep_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_rep_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_accounts_location', 'accounts', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_accounts_assigned_rep_id'), 'accounts', ['assigned_rep_id'], unique=False)
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=False)
    op.create_index(op.f('ix_accounts_status'), 'accounts', ['status'], unique=False)
    op.create_table('contacts',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_account_id'), 'contacts', ['account_id'], unique=False)
    op.create_geospatial_table('visits',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('rep_id', sa.Uuid(), nullable=True),
    sa.Column('location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('outcome', sa.Enum('no_contact', 'interested', 'not_interested', 'sample_given', 'order_placed', 'follow_up_needed', name='visit_outcome'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rep_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_visits_location', 'visits', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_visits_account_id'), 'visits', ['account_id'], unique=False)
    op.create_index(op.f('ix_visits_occurred_at'), 'visits', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_visits_rep_id'), 'visits', ['rep_id'], unique=False)
    op.create_table('samples',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('rep_id', sa.Uuid(), nullable=True),
    sa.Column('visit_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rep_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samples_account_id'), 'samples', ['account_id'], unique=False)
    op.create_index(op.f('ix_samples_occurred_at'), 'samples', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_samples_rep_id'), 'samples', ['rep_id'], unique=False)
    op.create_index(op.f('ix_samples_visit_id'), 'samples', ['visit_id'], unique=False)
    op.create_table('orders',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('rep_id', sa.Uuid(), nullable=True),
    sa.Column('order_type', sa.Enum('trial', 'repeat', name='order_type'), nullable=False),
    sa.Column('sample_id', sa.Uuid(), nullable=True),
    sa.Column('visit_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rep_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_account_id'), 'orders', ['account_id'], unique=False)
    op.create_index(op.f('ix_orders_occurred_at'), 'orders', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_orders_order_type'), 'orders', ['order_type'], unique=False)
    op.create_index(op.f('ix_orders_rep_id'), 'orders', ['rep_id'], unique=False)
    op.create_index(op.f('ix_orders_sample_id'), 'orders', ['sample_id'], unique=False)
    op.create_index(op.f('ix_orders_visit_id'), 'orders', ['visit_id'], unique=False)
    op.create_table('sample_items',
    sa.Column('sample_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sample_items_product_id'), 'sample_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_sample_items_sample_id'), 'sample_items', ['sample_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_sample_items_sample_id'), table_name='sample_items')
    op.drop_index(op.f('ix_sample_items_product_id'), table_name='sample_items')
    op.drop_table('sample_items')
    op.drop_index(op.f('ix_orders_visit_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_sample_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_rep_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_type'), table_name='orders')
    op.drop_index(op.f('ix_orders_occurred_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_account_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_samples_visit_id'), table_name='samples')
    op.drop_index(op.f('ix_samples_rep_id'), table_name='samples')
    op.drop_index(op.f('ix_samples_occurred_at'), table_name='samples')
    op.drop_index(op.f('ix_samples_account_id'), table_name='samples')
    op.drop_table('samples')
    op.drop_index(op.f('ix_visits_rep_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_occurred_at'), table_name='visits')
    op.drop_index(op.f('ix_visits_account_id'), table_name='visits')
    op.drop_geospatial_index('idx_visits_location', table_name='visits', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('visits')
    op.drop_index(op.f('ix_contacts_account_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_accounts_status'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_assigned_rep_id'), table_name='accounts')
    op.drop_geospatial_index('idx_accounts_location', table_name='accounts', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###

    # Alembic's drop_table does not drop the ENUM types created implicitly with
    # the tables, so drop them explicitly to keep downgrade/upgrade idempotent.
    for enum_name in ("order_type", "visit_outcome", "account_status",
                      "account_category", "user_role"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
