"""visit media

Revision ID: 64eece8ad7bc
Revises: f040c6166a44
Create Date: 2026-06-30 08:29:07.277614
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64eece8ad7bc'
down_revision: str | None = 'f040c6166a44'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit_media',
    sa.Column('visit_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_media_visit_id'), 'visit_media', ['visit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visit_media_visit_id'), table_name='visit_media')
    op.drop_table('visit_media')
    # ### end Alembic commands ###
