"""account status history

Revision ID: f040c6166a44
Revises: 4d8b94a729cb
Create Date: 2026-06-29 22:04:46.609114
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'f040c6166a44'
down_revision: str | None = '4d8b94a729cb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Reuse the existing account_status enum (created with the accounts table);
# create_type=False stops this migration from re-issuing CREATE TYPE.
account_status = postgresql.ENUM(
    'lead', 'in_discussion', 'sampled', 'trial', 'repeat', 'not_interested',
    name='account_status', create_type=False,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_status_history',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', account_status, nullable=False),
    sa.Column('to_status', account_status, nullable=False),
    sa.Column('changed_by_id', sa.Uuid(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_status_history_account_id'), 'account_status_history', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_status_history_changed_at'), 'account_status_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_account_status_history_changed_by_id'), 'account_status_history', ['changed_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_status_history_changed_by_id'), table_name='account_status_history')
    op.drop_index(op.f('ix_account_status_history_changed_at'), table_name='account_status_history')
    op.drop_index(op.f('ix_account_status_history_account_id'), table_name='account_status_history')
    op.drop_table('account_status_history')
    # ### end Alembic commands ###
