/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Accounts */
        get: operations["list_accounts_accounts_get"];
        put?: never;
        /** Create Account */
        post: operations["create_account_accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Account */
        get: operations["get_account_accounts__account_id__get"];
        put?: never;
        post?: never;
        /** Delete Account */
        delete: operations["delete_account_accounts__account_id__delete"];
        options?: never;
        head?: never;
        /** Update Account */
        patch: operations["update_account_accounts__account_id__patch"];
        trace?: never;
    };
    "/accounts/{account_id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Account Profile
         * @description Account overview: details + contacts + recent visit history + activity counts.
         */
        get: operations["account_profile_accounts__account_id__profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{account_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Status
         * @description Move an account through the funnel; records who/when in status history.
         *
         *     Allowed for the assigned rep (or any manager). Validates the transition.
         */
        post: operations["change_status_accounts__account_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{account_id}/status-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status History */
        get: operations["status_history_accounts__account_id__status_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{account_id}/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Contacts */
        get: operations["list_contacts_accounts__account_id__contacts_get"];
        put?: never;
        /** Create Contact */
        post: operations["create_contact_accounts__account_id__contacts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/{contact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Contact */
        delete: operations["delete_contact_contacts__contact_id__delete"];
        options?: never;
        head?: never;
        /** Update Contact */
        patch: operations["update_contact_contacts__contact_id__patch"];
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Products */
        get: operations["list_products_products_get"];
        put?: never;
        /** Create Product */
        post: operations["create_product_products_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product */
        get: operations["get_product_products__product_id__get"];
        put?: never;
        post?: never;
        /**
         * Deactivate Product
         * @description Soft-delete: flip is_active off so historical samples/orders keep the product.
         */
        delete: operations["deactivate_product_products__product_id__delete"];
        options?: never;
        head?: never;
        /** Update Product */
        patch: operations["update_product_products__product_id__patch"];
        trace?: never;
    };
    "/accounts/{account_id}/visits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Visits */
        get: operations["list_visits_accounts__account_id__visits_get"];
        put?: never;
        /**
         * Log Visit
         * @description Check in / log a visit. Attributed to the signed-in rep.
         */
        post: operations["log_visit_accounts__account_id__visits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/visits/{visit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Visit */
        get: operations["get_visit_visits__visit_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/visits/{visit_id}/media/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Presign Media Upload
         * @description Get a presigned PUT URL; the client uploads the photo straight to storage.
         */
        post: operations["presign_media_upload_visits__visit_id__media_presign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/visits/{visit_id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Media */
        get: operations["list_media_visits__visit_id__media_get"];
        put?: never;
        /**
         * Attach Media
         * @description Record an uploaded object against the visit (call after the PUT succeeds).
         */
        post: operations["attach_media_visits__visit_id__media_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{media_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Media */
        delete: operations["delete_media_media__media_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Activity Feed */
        get: operations["activity_feed_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{account_id}/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Samples */
        get: operations["list_samples_accounts__account_id__samples_get"];
        put?: never;
        /** Record Sample */
        post: operations["record_sample_accounts__account_id__samples_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{account_id}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orders */
        get: operations["list_orders_accounts__account_id__orders_get"];
        put?: never;
        /** Create Order */
        post: operations["create_order_accounts__account_id__orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe — confirms the API process is up.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Db
         * @description Readiness probe — confirms Postgres + PostGIS are reachable.
         */
        get: operations["health_db_health_db_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountCategory
         * @enum {string}
         */
        AccountCategory: "grocery_store" | "wholesaler" | "restaurant" | "caterer" | "vendor";
        /** AccountCreate */
        AccountCreate: {
            /** Name */
            name: string;
            category: components["schemas"]["AccountCategory"];
            /** @default lead */
            status: components["schemas"]["AccountStatus"];
            /** Address */
            address?: string | null;
            /** Notes */
            notes?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lng */
            lng?: number | null;
            /** Assigned Rep Id */
            assigned_rep_id?: string | null;
        };
        /** AccountOut */
        AccountOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            category: components["schemas"]["AccountCategory"];
            status: components["schemas"]["AccountStatus"];
            /** Address */
            address: string | null;
            /** Lat */
            lat: number | null;
            /** Lng */
            lng: number | null;
            /** Notes */
            notes: string | null;
            /** Last Verified At */
            last_verified_at: string | null;
            /** Assigned Rep Id */
            assigned_rep_id: string | null;
            /** Is Repeating */
            is_repeating: boolean;
            /** Repeat Order Count */
            repeat_order_count: number;
            /** Last Order At */
            last_order_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AccountProfile */
        AccountProfile: {
            account: components["schemas"]["AccountOut"];
            /** Contacts */
            contacts: components["schemas"]["ContactOut"][];
            /** Recent Visits */
            recent_visits: components["schemas"]["VisitOut"][];
            summary: components["schemas"]["ProfileSummary"];
        };
        /**
         * AccountStatus
         * @description Sample → Trial → Repeat funnel stages (Epic 4).
         * @enum {string}
         */
        AccountStatus: "lead" | "in_discussion" | "sampled" | "trial" | "repeat" | "not_interested";
        /** AccountUpdate */
        AccountUpdate: {
            /** Name */
            name?: string | null;
            category?: components["schemas"]["AccountCategory"] | null;
            status?: components["schemas"]["AccountStatus"] | null;
            /** Address */
            address?: string | null;
            /** Notes */
            notes?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lng */
            lng?: number | null;
            /** Assigned Rep Id */
            assigned_rep_id?: string | null;
        };
        /** ActivityEvent */
        ActivityEvent: {
            /**
             * Type
             * @enum {string}
             */
            type: "visit" | "sample" | "order";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Account Name */
            account_name: string;
            /** Rep Id */
            rep_id: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Detail */
            detail: string;
        };
        /** ActivityFeed */
        ActivityFeed: {
            /** Items */
            items: components["schemas"]["ActivityEvent"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** AttachMediaRequest */
        AttachMediaRequest: {
            /** Key */
            key: string;
            /** Content Type */
            content_type?: string | null;
        };
        /** ContactCreate */
        ContactCreate: {
            /** Name */
            name: string;
            /** Role */
            role?: string | null;
            /** Phone */
            phone?: string | null;
            /**
             * Is Primary
             * @default false
             */
            is_primary: boolean;
        };
        /** ContactOut */
        ContactOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Name */
            name: string;
            /** Role */
            role: string | null;
            /** Phone */
            phone: string | null;
            /** Is Primary */
            is_primary: boolean;
        };
        /** ContactUpdate */
        ContactUpdate: {
            /** Name */
            name?: string | null;
            /** Role */
            role?: string | null;
            /** Phone */
            phone?: string | null;
            /** Is Primary */
            is_primary?: boolean | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MediaOut */
        MediaOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Visit Id
             * Format: uuid
             */
            visit_id: string;
            /** Content Type */
            content_type: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** View Url */
            view_url: string;
        };
        /** OrderCreate */
        OrderCreate: {
            order_type: components["schemas"]["OrderType"];
            /** Items */
            items: components["schemas"]["OrderItemIn"][];
            /** Occurred At */
            occurred_at?: string | null;
            /** Sample Id */
            sample_id?: string | null;
            /** Visit Id */
            visit_id?: string | null;
        };
        /** OrderItemIn */
        OrderItemIn: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
        };
        /** OrderItemOut */
        OrderItemOut: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Product Name */
            product_name: string;
            /** Quantity */
            quantity: number;
            /** Unit Price */
            unit_price: number;
        };
        /** OrderOut */
        OrderOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Rep Id */
            rep_id: string | null;
            order_type: components["schemas"]["OrderType"];
            /** Sample Id */
            sample_id: string | null;
            /** Visit Id */
            visit_id: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Total Value */
            total_value: number;
            /** Currency */
            currency: string;
            /** Items */
            items: components["schemas"]["OrderItemOut"][];
        };
        /**
         * OrderType
         * @enum {string}
         */
        OrderType: "trial" | "repeat";
        /** Page[AccountOut] */
        Page_AccountOut_: {
            /** Items */
            items: components["schemas"]["AccountOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[ProductOut] */
        Page_ProductOut_: {
            /** Items */
            items: components["schemas"]["ProductOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** PresignRequest */
        PresignRequest: {
            /**
             * Content Type
             * @default image/jpeg
             */
            content_type: string;
        };
        /** PresignResponse */
        PresignResponse: {
            /** Key */
            key: string;
            /** Upload Url */
            upload_url: string;
            /**
             * Method
             * @default PUT
             */
            method: string;
        };
        /** ProductCreate */
        ProductCreate: {
            /** Name */
            name: string;
            /** Pack Size */
            pack_size?: string | null;
            /** Price */
            price?: number | null;
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** ProductOut */
        ProductOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Pack Size */
            pack_size: string | null;
            /** Price */
            price: number | null;
            /** Currency */
            currency: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProductUpdate */
        ProductUpdate: {
            /** Name */
            name?: string | null;
            /** Pack Size */
            pack_size?: string | null;
            /** Price */
            price?: number | null;
            /** Currency */
            currency?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** ProfileSummary */
        ProfileSummary: {
            /** Visits */
            visits: number;
            /** Samples */
            samples: number;
            /** Orders */
            orders: number;
            /** Last Visit At */
            last_visit_at: string | null;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** SampleCreate */
        SampleCreate: {
            /** Items */
            items: components["schemas"]["SampleItemIn"][];
            /** Occurred At */
            occurred_at?: string | null;
            /** Visit Id */
            visit_id?: string | null;
        };
        /** SampleItemIn */
        SampleItemIn: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
        };
        /** SampleItemOut */
        SampleItemOut: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Product Name */
            product_name: string;
            /** Quantity */
            quantity: number;
        };
        /** SampleOut */
        SampleOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Rep Id */
            rep_id: string | null;
            /** Visit Id */
            visit_id: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Items */
            items: components["schemas"]["SampleItemOut"][];
        };
        /** StatusChangeRequest */
        StatusChangeRequest: {
            status: components["schemas"]["AccountStatus"];
            /** Note */
            note?: string | null;
        };
        /** StatusHistoryOut */
        StatusHistoryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            from_status: components["schemas"]["AccountStatus"];
            to_status: components["schemas"]["AccountStatus"];
            /** Changed By Id */
            changed_by_id: string | null;
            /**
             * Changed At
             * Format: date-time
             */
            changed_at: string;
            /** Note */
            note: string | null;
        };
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            role: components["schemas"]["UserRole"];
            /** Is Active */
            is_active: boolean;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "manager" | "rep";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VisitCreate */
        VisitCreate: {
            /** Notes */
            notes?: string | null;
            outcome?: components["schemas"]["VisitOutcome"] | null;
            /** Lat */
            lat?: number | null;
            /** Lng */
            lng?: number | null;
            /** Occurred At */
            occurred_at?: string | null;
        };
        /** VisitOut */
        VisitOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Rep Id */
            rep_id: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            outcome: components["schemas"]["VisitOutcome"] | null;
            /** Notes */
            notes: string | null;
            /** Lat */
            lat?: number | null;
            /** Lng */
            lng?: number | null;
        };
        /**
         * VisitOutcome
         * @enum {string}
         */
        VisitOutcome: "no_contact" | "interested" | "not_interested" | "sample_given" | "order_placed" | "follow_up_needed";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    list_accounts_accounts_get: {
        parameters: {
            query?: {
                category?: components["schemas"]["AccountCategory"] | null;
                status?: components["schemas"]["AccountStatus"] | null;
                /** @description Search by account name */
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AccountOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_account_accounts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_account_accounts__account_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_account_accounts__account_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_account_accounts__account_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    account_profile_accounts__account_id__profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_status_accounts__account_id__status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_history_accounts__account_id__status_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusHistoryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_contacts_accounts__account_id__contacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_contact_accounts__account_id__contacts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_contact_contacts__contact_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_contact_contacts__contact_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_products_products_get: {
        parameters: {
            query?: {
                /** @description Search by product name */
                q?: string | null;
                include_inactive?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ProductOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_product_products_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_products__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_product_products__product_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_products__product_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_visits_accounts__account_id__visits_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_visit_accounts__account_id__visits_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VisitCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_visit_visits__visit_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    presign_media_upload_visits__visit_id__media_presign_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visit_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresignRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_media_visits__visit_id__media_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attach_media_visits__visit_id__media_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visit_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachMediaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_media_media__media_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_users_get: {
        parameters: {
            query?: {
                role?: components["schemas"]["UserRole"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activity_feed_activity_get: {
        parameters: {
            query?: {
                rep_id?: string | null;
                /** @description Cursor: only events before this */
                before?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityFeed"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_samples_accounts__account_id__samples_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_sample_accounts__account_id__samples_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SampleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_accounts__account_id__orders_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_order_accounts__account_id__orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_db_health_db_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
